export interface Property {
    id?: number; // id may be undefined because it can be auto-generated by the database
    name: string;
    location: string;
    price: string;
    description: string;
    createdAt?: Date | null; // Optional and can be null
    updatedAt?: Date; // Optional
  }
  